import { useState } from "react";
import Context from "./Context";

const StateByContext = ({ children }) => {
  const [courseVal, setCourseVal] = useState({
    course: "",
    experience: "",
  });

  const [catTechName, setCatTechName] = useState("");
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [logInData, setLogInData] = useState({});
  const [loading, setLoading] = useState(false);
  const [featuredData, setFeaturedData] = useState({});
  const [totalAppliedJobs, setTotalAppliedJobs] = useState("");

  // const featuredJobs = [
  //   {
  //     id: 1,
  //     title: "Node.js Developer",
  //     companyName: "Mobulous Technologies Pvt Ltd",
  //     hrName: "Preeti Mishra",
  //     hrEmail: "preeti.mishra@modulous.com",
  //     contactNumber: "7805063968",
  //     category: "MERN Stack",
  //     experienceRequired: 2,
  //     postedDate: "2024-10-21",
  //     expiryDate: "2024-10-28",
  //     jobDescription:
  //       "We are looking for experienced candidates with 1.5 to 2 years of Node.js development experience.",
  //   },
  //   {
  //     id: 2,
  //     title: "React.js Developer",
  //     companyName: "Tech Innovators",
  //     hrName: "Rahul Kumar",
  //     hrEmail: "rahul.kumar@techinnovators.com",
  //     contactNumber: "7896541230",
  //     category: "Frontend Developer",
  //     experienceRequired: 3,
  //     postedDate: "2024-10-15",
  //     expiryDate: "2024-10-30",
  //     jobDescription:
  //       "We are looking for a skilled React.js developer with at least 3 years of experience in building scalable frontend applications.",
  //   },
  //   {
  //     id: 3,
  //     title: "Full Stack Developer",
  //     companyName: "Softgrid Solutions",
  //     hrName: "Anjali Verma",
  //     hrEmail: "anjali.verma@softgrid.com",
  //     contactNumber: "8541236974",
  //     category: "Full Stack Developer",
  //     experienceRequired: 4,
  //     postedDate: "2024-10-18",
  //     expiryDate: "2024-11-01",
  //     jobDescription:
  //       "Looking for a full stack developer with expertise in both frontend and backend technologies, specifically MERN stack.",
  //   },
  //   {
  //     id: 4,
  //     title: "Backend Developer",
  //     companyName: "CodeCrafters",
  //     hrName: "Sumit Sharma",
  //     hrEmail: "sumit.sharma@codecrafters.com",
  //     contactNumber: "9012365874",
  //     category: "Backend Developer",
  //     experienceRequired: 2,
  //     postedDate: "2024-10-20",
  //     expiryDate: "2024-10-31",
  //     jobDescription:
  //       "We need a backend developer with experience in Node.js and database management. Candidates should have 2 years of experience.",
  //   },
  //   {
  //     id: 5,
  //     title: "Frontend Developer",
  //     companyName: "Pixel Tech",
  //     hrName: "Neha Gupta",
  //     hrEmail: "neha.gupta@pixeltech.com",
  //     contactNumber: "9912586347",
  //     category: "Frontend Developer",
  //     experienceRequired: 1,
  //     postedDate: "2024-10-19",
  //     expiryDate: "2024-10-27",
  //     jobDescription:
  //       "We are seeking a Frontend Developer with at least 1 year of experience in React.js and JavaScript frameworks.",
  //   },
  //   {
  //     id: 6,
  //     title: "PYTHON",
  //     companyName: "Drag Tech",
  //     hrName: "Neha Gupta",
  //     hrEmail: "neha.gupta@pixeltech.com",
  //     contactNumber: "9912586347",
  //     category: "PYTHON",
  //     experienceRequired: 1,
  //     postedDate: "2024-10-19",
  //     expiryDate: "2024-10-27",
  //     jobDescription: "We are seeking a EXPERT of PYTHON.",
  //   },
  //   {
  //     id: 7,
  //     title: "Java Developer",
  //     companyName: "Tech Solutions Inc.",
  //     hrName: "Ravi Singh",
  //     hrEmail: "ravi.singh@techsolutions.com",
  //     contactNumber: "8123456789",
  //     category: "JAVA",
  //     experienceRequired: 3,
  //     postedDate: "2024-10-24",
  //     expiryDate: "2024-11-10",
  //     jobDescription:
  //       "We are looking for a Java Developer with strong knowledge of Java frameworks and experience in building enterprise applications.",
  //   },
  //   {
  //     id: 8,
  //     title: "Mobile App Developer",
  //     companyName: "InnovaTech",
  //     hrName: "Sita Rao",
  //     hrEmail: "sita.rao@innovatech.com",
  //     contactNumber: "9988776655",
  //     category: "ANDROID",
  //     experienceRequired: 2,
  //     postedDate: "2024-10-22",
  //     expiryDate: "2024-11-05",
  //     jobDescription:
  //       "Seeking a Mobile App Developer proficient in Android development with experience in Kotlin or Java.",
  //   },
  //   {
  //     id: 9,
  //     title: "Software Testing Engineer",
  //     companyName: "Quality Tech",
  //     hrName: "Karan Mehta",
  //     hrEmail: "karan.mehta@qualitytech.com",
  //     contactNumber: "8456781234",
  //     category: "SOFTWARE TESTING",
  //     experienceRequired: 2,
  //     postedDate: "2024-10-25",
  //     expiryDate: "2024-11-15",
  //     jobDescription:
  //       "We are hiring a Software Testing Engineer with experience in manual and automated testing processes.",
  //   },
  //   {
  //     id: 10,
  //     title: "Data Scientist",
  //     companyName: "Data Insights Corp.",
  //     hrName: "Aditi Sharma",
  //     hrEmail: "aditi.sharma@datainsights.com",
  //     contactNumber: "8765432109",
  //     category: "DATA SCIENCE",
  //     experienceRequired: 3,
  //     postedDate: "2024-10-23",
  //     expiryDate: "2024-11-20",
  //     jobDescription:
  //       "Looking for a Data Scientist with experience in machine learning, data analysis, and visualization techniques.",
  //   },
  //   {
  //     id: 11,
  //     title: "DevOps Engineer",
  //     companyName: "Cloud Solutions",
  //     hrName: "Vikram Patel",
  //     hrEmail: "vikram.patel@cloudsolutions.com",
  //     contactNumber: "6543210987",
  //     category: "DEVOPS",
  //     experienceRequired: 4,
  //     postedDate: "2024-10-26",
  //     expiryDate: "2024-11-25",
  //     jobDescription:
  //       "We are seeking a DevOps Engineer with a strong background in CI/CD pipelines, containerization, and cloud services.",
  //   },
  //   {
  //     id: 12,
  //     title: "Full Stack Developer",
  //     companyName: "Web Innovators",
  //     hrName: "Neeraj Sharma",
  //     hrEmail: "neeraj.sharma@webinnovators.com",
  //     contactNumber: "7890123456",
  //     category: "MERN STACK",
  //     experienceRequired: 3,
  //     postedDate: "2024-10-28",
  //     expiryDate: "2024-11-30",
  //     jobDescription:
  //       "We are looking for a Full Stack Developer with expertise in both frontend (React.js) and backend (Node.js) technologies.",
  //   },
  // ];

  const courses = [
    "MERN STACK",
    "PYTHON",
    "REACT JS",
    "PHP",
    "JAVA",
    ".NET",
    "SOFTWARE TESTING",
    "SALES FORCE",
    "ANDROID",
    "IOS",
    "FLUTTER",
    "DEVOPS",
    "DATA ANALYTICS",
    "DATA SCIENCE",
    "JAVASCRIPT",
    "BOOTSTRAP",
  ];
  const experience = [
    "Fresher",
    "1 Year",
    "2 Year",
    "3 Year",
    "4 Year",
    "5 Year",
    "6 + Year",
  ];

  const testimonials = [
    {
      name: "Margaret Lawson",
      position: "Creative Director",
      image:
        "https://www.technokri.com/assets/img/testmonial/testimonial-founder.png",
      quote:
        "I am at an age where I just want to be fit and healthy. Our bodies are our responsibility! Start caring for your body, and it will care for you. Eat clean, work out hard.",
    },
    {
      name: "Vishal Parmar",
      position: "Creative Director",
      image: "https://www.technokri.com/assets/img/testmonial/3.jpg",
      quote:
        "Staying fit is a lifestyle choice. I believe in regular exercise, clean eating, and mental peace to maintain a healthy balance.",
    },
    {
      name: "John Doe",
      position: "Marketing Head",
      image:
        "https://www.technokri.com/assets/img/testmonial/testimonial-founder.png",
      quote:
        "Fitness is about consistency and motivation. If you stay on track, your body will repay you in the long run. Eat well, work out, and maintain a positive mindset.",
    },
  ];

  const technologies = [
    {
      name: "MERN Stack",
      id: 1,
      jobs: "2",
      availability: "yes",
      url: "https://www.technokri.com/admin/uploads/98279982efd29ba993f37e030318597e.jpg",
      profile: "Mernstack Developer",
      technology: "MERN Stack",
      describtion: "MERN STACK DEVELOPER",
    },
    {
      id: 2,
      name: "PYTHON Jobs",
      jobs: "1",
      url: "https://www.technokri.com/admin/uploads/8bd78d175560f64ee7ac0b5aafbfe432.jpg",
      profile: "PYTHON DEVELOPER",
      availability: "yes",
      technology: "PYTHON",
      describtion:
        "PYTHON DEVELOPER PYTHON FRAMEWORKS AND DJANGO AND FLASK AND RESTFUL API AND HTM ,CSS,JAVA SCRPIT.",
    },
    {
      id: 3,
      name: "REACT JS Jobs",
      jobs: "2",
      availability: "yes",
      url: "https://www.technokri.com/admin/uploads/26d3cd8b9a59a1565d2e2b95c0f80f1d.png",
      profile: "REACT JS",
      technology: "REACT JS",
      describtion: "Advance React",
    },
    {
      id: 4,
      name: "PHP Jobs",
      jobs: "1",
      availability: "no",
      url: "https://www.technokri.com/admin/uploads/53928add6b1876a300bdbf48d288b296.jpg",
      profile: "PHP",
      technology: "PHP",
      describtion: "PHP Developers",
    },
    {
      id: 5,
      name: "JAVA Jobs",
      jobs: "3",
      availability: "no",
      url: "https://www.technokri.com/admin/uploads/f59043560825639a01d61c721fe4459a.jpg",
      profile: " JAVA DEVELOPER",
      technology: "JAVA",
      describtion: ": Java full stack Developer",
    },
    {
      id: 6,
      name: ".NET Jobs",
      availability: "no",
      jobs: "0",
      url: "https://www.technokri.com/admin/uploads/ffc7553f60708a6d8e91c5e2dcc032f6.jpg",
      profile: ".NET",
      technology: ".NET",
      describtion: ".NET ",
    },
    {
      id: 7,
      name: "SOFTWARE TESTING Jobs",
      availability: "no",
      jobs: "2",
      url: "https://www.technokri.com/admin/uploads/e8ad6e3a6fb9410090190a4c8b3f990c.jpg",
      profile: "SOFTWARE TESTING",
      technology: "SOFTWARE TESTING",
      describtion: "SOFTWARE TESTING C21 MALL VIJAY NAGAR INDORE",
    },
    {
      id: 8,
      name: "SALES FORCE Jobs",
      jobs: "2",
      availability: "no",
      url: "https://www.technokri.com/admin/uploads/4c8bac6c244a97dcebd9faa21eab428f.jpg",
      profile: "SALES FORCE",
      technology: "SALES FORCE",
      describtion: "Salesforce Developer Fresher /Experienced",
    },
    {
      id: 9,
      name: "ANDROID Jobs",
      jobs: "2",
      availability: "no",
      url: "https://www.technokri.com/admin/uploads/48fd9f019dd5ecd80f7d826ee5da7142.jpg",
      profile: "ANDROID DEVELOPER",
      technology: "ANDROID",
      describtion: "ANDROID DEVELOPER C21 MALL VIJAY NAGAR INDORE",
    },
    {
      id: 10,
      name: "IOS Jobs",
      jobs: "3",
      url: "https://www.technokri.com/admin/uploads/3ae30017764bcff4009afd0490944763.jpg",
      profile: "IOS",
      availability: "no",
      technology: "IOS",
      describtion: "Full IOS",
    },
    {
      id: 11,
      name: "FLUTTER Jobs",
      jobs: "2",
      availability: "no",
      url: "https://www.technokri.com/admin/uploads/42ca9f8619fa3ce71ea7d230b721a2dc.jpg",
      profile: "FLUTTER Developer",
      technology: "FLUTTER",
      describtion: "FLUTTER DEV",
    },
    {
      id: 12,
      name: "DEVOPS Jobs",
      availability: "no",
      jobs: "1",
      url: "https://www.technokri.com/admin/uploads/3cf0b543818be1150f358233036011d5.jpg",
      profile: "DEVOPS",
      technology: "DEVOPS",
      describtion: "DEVOPS",
    },
    {
      id: 13,
      name: "DATA ANALYTICS Jobs",
      jobs: "1",
      availability: "no",
      url: "https://www.technokri.com/admin/uploads/9e4e76c1aa8e65859eb3aa84fdf5742a.jpg",
      profile: "DATA ANALYTICS",
      technology: "DATA ANALYTICS",
      describtion: "DATA ANALYTICS",
    },
    {
      id: 14,
      name: "DATA SCIENCE Jobs",
      jobs: "3",
      availability: "no",
      url: "https://www.technokri.com/admin/uploads/d0dfa8c3b8ed016418934d60c0908401.jpg",
      profile: "DATA SCIENCE",
      technology: "DATA SCIENCE",
      describtion: "DATA SCIENCE",
    },
    {
      id: 15,
      name: "JAVASCRIPT Jobs",
      availability: "yes",
      jobs: "1",
      url: "https://www.technokri.com/admin/uploads/470de7eba6c8b33c816eda2471f812c4.jpg",
      profile: "JAVASCRIPT",
      technology: "JAVASCRIPT",
      describtion: "JAVASCRIPT",
    },
    {
      id: 16,
      name: "BOOTSTRAP Jobs ",
      jobs: "0",
      availability: "no",
      url: "https://www.technokri.com/admin/uploads/a52c37593327035d70fe7a411fe4f575.jpg",
      profile: "DESIGNER",
      technology: "BOOTSTRAP",
      describtion: "BOOTSTRAP",
    },
  ];

  const availableJobs = [
    {
      technology: "PYTHON",
      developer: "PYTHON DEVELOPER",
      id: "123",
      availability: "yes",
      posted: "Posted 2024-09-27",
      experience: "2 Year",
      describtion: "PYTHON DEVELOPER",
    },
    {
      technology: "MERN STACK",
      developer: "MERN STACK DEVELOPER",
      availability: "yes",
      id: "124",
      posted: "Posted 2024-10-26",
      experience: "Fresher",
      describtion: "MERN STACK DEVELOPER",
    },
    {
      technology: "MERN STACK",
      developer: "NODE JS",
      id: "125",
      availability: "no",
      experience: "4 Year",
      posted: "Posted 2024-10-26",
      describtion: "BACKEND DEVELOPER",
    },
    {
      technology: "REACT JS",
      id: "126",
      developer: "REACT JS",
      experience: "Fresher",
      availability: "no",
      posted: "Posted 2024-07-24",
      describtion: "FRONTEND DEVELOPER",
    },
    {
      technology: "REACT JS",
      developer: "REACT JS",
      id: "127",
      experience: "Fresher",
      posted: "Posted 2024-12-19",
      availability: "yes",
      describtion: "FRONTEND DEVELOPER",
    },
    {
      technology: "JAVA",
      experience: "Fresher",
      id: "128",
      developer: "JAVA DEVELOPER",
      availability: "no",
      posted: "Posted 2024-11-26",
      describtion: "JAVA DEVELOPER",
    },
    {
      technology: "JAVA",
      developer: "CORE JAVA",
      id: "129",
      experience: "2 Year",
      availability: "yes",
      posted: "Posted 2024-11-26",
      describtion: "JAVA CORE",
    },
    {
      technology: "JAVA",
      developer: "ADVANCE JAVA",
      id: "130",
      experience: "5 Year",
      availability: "no",
      posted: "Posted 2024-11-26",
      describtion: "ADVANCE JAVA",
    },
    {
      technology: "DEVOPS",
      id: "131",
      developer: "DEVOPS",
      experience: "5 Year",
      availability: "yes",
      posted: "Posted 2024-11-26",
      describtion: "DEVOPS",
    },
    {
      technology: "ANDROID",
      id: "132",
      developer: "ANDROID",
      experience: "5 Year",
      availability: "no",
      posted: "Posted 2024-11-26",
      describtion: "ANDROID",
    },

    {
      technology: "ANDROID",
      id: "133",
      developer: "ANDROID",
      experience: "5 Year",
      availability: "yes",
      posted: "Posted 2024-11-29",
      describtion: "ANDROID DEVELOPER ",
    },
    {
      technology: "IOS",
      id: "160",
      developer: "IOS",
      experience: "5 Year",
      availability: "yes",
      posted: "Posted 2024-11-29",
      describtion: "IOS DEVELOPER ",
    },
    {
      technology: "IOS",
      id: "161",
      developer: "IOS",
      experience: "5 Year",
      availability: "no",
      posted: "Posted 2024-11-29",
      describtion: "IOS DEVELOPER ",
    },
    {
      technology: "IOS",
      id: "162",
      developer: "IOS",
      experience: "2 Year",
      availability: "no",
      posted: "Posted 2024-11-29",
      describtion: "IOS DEVELOPER ",
    },

    {
      technology: "SALES FORCE",
      developer: "SALES FORCE",
      id: "134",
      experience: "5 Year",
      availability: "no",
      posted: "Posted 2024-11-26",
      describtion: "SALES FORCE",
    },
    {
      technology: "DATA ANALYTICS",
      developer: "DATA ANALYST",
      id: "164",
      experience: "3 Year",
      availability: "yes",
      posted: "Posted 2024-11-25",
      describtion: "DATA ANALYTICS",
    },
    {
      technology: "DATA SCIENCE",
      developer: "DATA SCIENCE",
      id: "165",
      experience: "5 Year",
      availability: "yes",
      posted: "Posted 2024-11-25",
      describtion: "DATA SCIENCE",
    },
    {
      technology: "DATA SCIENCE",
      developer: "JUNIOR DATA SCIENCE",
      id: "166",
      experience: "5 Year",
      availability: "no",
      posted: "Posted 2024-10-25",
      describtion: "DATA SCIENCE",
    },
    {
      technology: "DATA SCIENCE",
      developer: "SENIOR DATA SCIENCE",
      id: "167",
      experience: "5 Year",
      availability: "no",
      posted: "Posted 2024-09-25",
      describtion: "DATA SCIENCE",
    },
    {
      technology: "JAVASCRIPT",
      developer: "JAVASCRIPT",
      id: "168",
      experience: "1 Year",
      availability: "yes",
      posted: "Posted 2024-09-25",
      describtion: "JAVASCRIPT",
    },
    {
      technology: "BOOTSTRAP",
      developer: "BOOTSTRAP",
      id: "169",
      experience: "4 Year",
      availability: "yes",
      posted: "Posted 2024-09-25",
      describtion: "BOOTSTRAP",
    },

    {
      technology: "FLUTTER",
      developer: "FLUTTER",
      id: "162",
      experience: "1 Year",
      availability: "yes",
      posted: "Posted 2024-11-26",
      describtion: "FLUTTER",
    },
    {
      technology: "FLUTTER",
      developer: "FLUTTER",
      id: "163",
      experience: "5 Year",
      availability: "no",
      posted: "Posted 2024-11-26",
      describtion: "FLUTTER",
    },
    {
      technology: "SALES FORCE",
      developer: "SALES FORCE",
      id: "135",
      experience: "5 Year",
      availability: "yes",
      posted: "Posted 2024-11-26",
      describtion: "SALES FORCE",
    },
    {
      technology: "SOFTWARE TESTING",
      id: "135",
      developer: "SOFTWARE TESTING",
      experience: "2 Year",
      availability: "yes",
      posted: "Posted 2024-11-26",
      describtion: "SOFTWARE TESTING",
    },
    {
      technology: "SOFTWARE TESTING",
      developer: "SOFTWARE TESTING",
      id: "136",
      experience: "1 Year",
      availability: "no",
      posted: "Posted 2024-11-28",
      describtion: "SOFTWARE TESTING",
    },
    {
      technology: "PHP",
      developer: "PHP Developer",
      id: "136",
      experience: "1 Year",
      availability: "yes",
      posted: "Posted 2024-11-28",
      describtion: "experienced php developer",
    },
  ];

  const jobs = [
    {
      id: 76,
      companyImage: "admin/uploads/42ca9f8619fa3ce71ea7d230b721a2dc.jpg",
      title: "FLUTTER DEVELOPER",
      hrName: "Dev Sharma",
      hrEmail: "dev77@gmail.com",
      contact: "9827064110",
      technology: "FLUTTER",
      category: "MOBILE APP DEVELOPMENT",
      description:
        "No Bond Policy, 5 Days Working, Excellent Working Environment",
      expiry: "2024-08-31",
      companyName: "CLOUDWAPP TECHNOLOGIES",
      experience: "1",
      posted: "23 days ago",
    },
    {
      id: 75,
      companyImage: "admin/uploads/98279982efd29ba993f37e030318597e.jpg",
      title: "MERN DEVELOPER",
      companyName: "SOFTGRID",
      hrName: "Shweta Sharma",
      technology: "MERN Stack",
      hrEmail: "shweta.sharma@softgrid.com",
      contact: "9823456789",
      category: "MERN STACK",
      description: "Flexible Working Hours, Great Team Environment",
      expiry: "2024-09-01",
      experience: "0",
      posted: "23 days ago",
    },
    {
      id: 74,
      companyImage: "admin/uploads/8bd78d175560f64ee7ac0b5aafbfe432.jpg",
      title: "PYTHON DEVELOPER",
      hrName: "Ravi Singh",
      technology: "PYTHON",
      hrEmail: "ravi.singh@bluecursor.com",
      contact: "9801234567",
      category: "PYTHON",
      description: "Growth-Oriented Role, 5 Days Working",
      expiry: "2024-08-29",
      companyName: "BLUECURSOR INFOTECH PVT. LTD.",
      experience: "2",
      posted: "20 days ago",
    },
    {
      id: 73,
      companyImage: "admin/uploads/4c8bac6c244a97dcebd9faa21eab428f.jpg",
      technology: "SALES FORCE",

      title: "SALESFORCE DEVELOPER",
      hrName: "Amit Roy",
      hrEmail: "amit.roy@omniforce.com",
      contact: "9845671234",
      category: "CRM DEVELOPMENT",
      description: "Friendly Environment, Competitive Salary",
      expiry: "2024-09-15",
      companyName: "OMNIFORCE TECHNOLOGIES",
      experience: "2",
      posted: "18 days ago",
    },
    {
      id: 72,
      companyImage: "admin/uploads/26d3cd8b9a59a1565d2e2b95c0f80f1d.png",
      title: "REACT JS DEVELOPER",
      companyName: "PIXEL TECH",
      technology: "REACT JS",

      hrName: "Priya Kapoor",
      hrEmail: "priya.kapoor@pixeltech.com",
      contact: "9876543210",
      category: "FRONTEND DEVELOPMENT",
      description: "5 Days Working, Learning Opportunities",
      expiry: "2024-09-10",
      experience: "0",
      posted: "22 days ago",
    },
    {
      id: 71,
      companyImage: "admin/uploads/1234abc.jpg",
      title: "JAVA DEVELOPER",
      hrName: "Meena Gupta",
      hrEmail: "meena.gupta@techcode.com",
      contact: "9812345678",
      technology: "JAVA",

      category: "BACKEND DEVELOPMENT",
      description: "Hybrid Work Model, Team Building Activities",
      expiry: "2024-09-05",
      companyName: "TECHCODE SOLUTIONS",
      experience: "3",
      posted: "15 days ago",
    },
    {
      id: 70,
      companyImage: "admin/uploads/5678def.jpg",
      title: "DEVOPS ENGINEER",
      hrName: "Rahul Khanna",
      hrEmail: "rahul.khanna@devcorp.com",
      technology: "DEVOPS",

      contact: "9823456780",
      category: "DEVOPS",
      description: "Performance Bonus, Dynamic Work Environment",
      expiry: "2024-09-20",
      companyName: "DEVCORP",
      experience: "1",
      posted: "10 days ago",
    },
    {
      id: 69,
      companyImage: "admin/uploads/9101ghi.jpg",
      title: "JAVASCRIPT",
      hrName: "Sunita Rao",
      hrEmail: "sunita.rao@webdynamics.com",
      contact: "9876504321",
      category: "JAVASCRIPT",
      technology: "JAVASCRIPT",

      description: "Competitive Salary, Growth-Oriented Team",
      expiry: "2024-09-12",
      companyName: "WEB DYNAMICS",
      experience: "2",
      posted: "12 days ago",
    },
    {
      id: 68,
      companyImage: "admin/uploads/1112jkl.jpg",
      title: "IOS DEVELOPER",
      hrName: "Kunal Sharma",
      hrEmail: "kunal.sharma@backendhub.com",
      contact: "9845678912",
      technology: "IOS",

      category: "IOS DEVELOPMENT",
      description: "Great Team, Flexible Working Hours",
      expiry: "2024-09-25",
      companyName: "IOS HUB",
      experience: "2",
      posted: "8 days ago",
    },
    {
      id: 67,
      companyImage: "admin/uploads/php_developer.jpg",
      title: "PHP DEVELOPER",
      hrName: "Rajesh Kumar",
      hrEmail: "rajesh.kumar@websolutions.com",
      contact: "9801234560",
      category: "PHP",
      technology: "PHP",

      description: "Remote Working, Flexible Hours",
      expiry: "2024-09-30",
      companyName: "WEB SOLUTIONS",
      experience: "1",
      posted: "5 days ago",
    },
    {
      id: 66,
      companyImage: "admin/uploads/dotnet_developer.jpg",
      title: ".NET DEVELOPER",
      hrName: "Rina Patel",
      hrEmail: "rina.patel@codetech.com",
      contact: "9876543211",
      category: ".NET",
      technology: ".NET",

      description: "Growth-Oriented Role, 5 Days Working",
      expiry: "2024-09-28",
      companyName: "CODE TECH SOLUTIONS",
      experience: "2",
      posted: "7 days ago",
    },
    {
      id: 65,
      companyImage: "admin/uploads/software_testing.jpg",
      title: "SOFTWARE TEST ENGINEER",
      hrName: "Amit Verma",
      hrEmail: "amit.verma@testhub.com",
      contact: "9812345679",
      category: "SOFTWARE TESTING",
      technology: "SOFTWARE TESTING",

      description: "Career Growth, Performance Bonus",
      expiry: "2024-09-27",
      companyName: "TEST HUB",
      experience: "1",
      posted: "10 days ago",
    },
    {
      id: 64,
      companyImage: "admin/uploads/android_developer.jpg",
      title: "ANDROID",
      hrName: "Sonia Gupta",
      hrEmail: "sonia.gupta@mobiletech.com",
      contact: "9823456781",
      category: "ANDROID",
      description: "Work-Life Balance, Growth Opportunities",
      expiry: "2024-09-24",
      companyName: "ANDROID HUB",
      technology: "ANDROID",

      experience: "2",
      posted: "8 days ago",
    },
    {
      id: 63,
      companyImage: "admin/uploads/ios_developer.jpg",
      title: "DATA SCIENCE",
      technology: "DATA SCIENCE",
      hrName: "Nitin Khurana",
      hrEmail: "nitin.khurana@applelabs.com",
      contact: "9809876543",
      category: "DATA SCIENCE",
      description: "Learning Opportunities, Flexible Hours",
      expiry: "2024-09-22",
      companyName: "WORLD SCIENCE CORPS",
      experience: "5",
      posted: "12 days ago",
    },
    {
      id: 62,
      companyImage: "admin/uploads/ios_developer.jpg",
      title: "DATA ANALYTICS",
      technology: "DATA ANALYTICS",
      hrName: "Aamn Shah",
      hrEmail: "aman.shah@applelabs.com",
      contact: "9809876543",
      category: "DATA ANALYTICS",
      description: "Learning Opportunities, Flexible Hours",
      expiry: "2024-09-22",
      companyName: "DATA ANALYTICS",
      experience: "3",
      posted: "12 days ago",
    },

    {
      id: 61,
      companyImage: "admin/uploads/data_science.jpg",
      title: "BOOTSTRAP",
      hrName: "Priya Sen",
      hrEmail: "priya.sen@datasciencehub.com",
      contact: "9845123789",
      category: "BOOTSTRAP",
      description: "5 Days Working, Attractive Salary",
      expiry: "2024-09-18",
      companyName: "HUB",
      experience: "3",
      technology: "BOOTSTRAP",

      posted: "17 days ago",
    },
    {
      id: 60,
      companyImage: "admin/uploads/js_developer.jpg",
      title: "JAVASCRIPT DEVELOPER",
      hrName: "Arjun Malik",
      hrEmail: "arjun.malik@webdynamics.com",
      contact: "9812347654",
      category: "JAVASCRIPT",
      description: "Dynamic Team, Flexible Hours",
      expiry: "2024-09-15",
      companyName: "WEB DYNAMICS",
      experience: "2",
      technology: "JAVASCRIPT",

      posted: "20 days ago",
    },
    {
      id: 59,
      companyImage: "admin/uploads/bootstrap_expert.jpg",
      title: "ANDROID",
      hrName: "Geeta Pandey",
      hrEmail: "geeta.pandey@designhub.com",
      contact: "9871234560",
      technology: "ANDROID",

      category: "ANDROID",
      description: "Attractive Salary, Skill Development",
      expiry: "2024-09-13",
      companyName: "ANDROID HUB",
      experience: "1",
      posted: "22 days ago",
    },
  ];
  return (
    <Context.Provider
      value={{
        courses,
        catTechName,
        setCatTechName,

        experience,
        availableJobs,
        technologies,
        testimonials,
        courseVal,
        setCourseVal,
        isLoggedIn,
        setIsLoggedIn,
        logInData,
        setLogInData,
        loading,
        setLoading,
        // featuredJobs,
        featuredData,
        setFeaturedData,
        jobs,
        totalAppliedJobs,
        setTotalAppliedJobs,
      }}
    >
      {children}
    </Context.Provider>
  );
};

export default StateByContext;
